# Generated by Django 5.0.6 on 2026-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.CharField(help_text='e.g. Kochi', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_url',
            field=models.CharField(default='#', help_text='Link for "More Info" button', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_point',
            field=models.CharField(help_text='e.g. Thrissur', max_length=150),
        ),
    ]
