# Generated by Django 5.0.6 on 2026-05-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorybottomsection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
        migrations.DeleteModel(
            name='ProductCategoryAbout',
        ),
        migrations.DeleteModel(
            name='ProductCategoryBottomSection',
        ),
    ]
