# Generated by Django 5.0.6 on 2026-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Button label e.g. "Explore Now"', max_length=80),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Button link URL or slug', max_length=300),
        ),
    ]
