# Generated by Django 5.0.6 on 2026-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mainbanner_cta_label_alter_mainbanner_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Mobile-optimised image (portrait crop). Falls back to main image if left empty.', null=True, upload_to='home/banners/mobile/'),
        ),
    ]
