# Generated by Django 5.0.6 on 2026-06-30 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title if left blank. Used in the URL.', max_length=320, unique=True)),
                ('author', models.CharField(default='Admin', help_text='Shown as the by-line, e.g. "Admin".', max_length=120)),
                ('featured_image', models.ImageField(help_text='Main image — used on the listing card, the POPULAR sidebar thumbnail and the detail page.', upload_to='blog/featured/')),
                ('body_image', models.ImageField(blank=True, help_text='Optional secondary image shown next to the body text on the detail page.', null=True, upload_to='blog/body/')),
                ('body_image_caption', models.CharField(blank=True, help_text='Caption under the body image, e.g. "1/3 Scenic riding route captured".', max_length=200)),
                ('excerpt', models.CharField(help_text='Short preview shown on the listing card / sidebar.', max_length=300)),
                ('intro', models.TextField(blank=True, help_text='Lead paragraph shown directly under the title on the detail page.')),
                ('highlight', models.CharField(blank=True, help_text='The large RED sub-heading on the detail page (optional).', max_length=300)),
                ('body', models.TextField(help_text='Main article content. HTML is allowed — this is rendered as raw HTML on the inner page (use <p>, <h3>, <strong>, <ul>, etc.).')),
                ('meta_description', models.CharField(blank=True, help_text='Optional description for the page <meta> tag / link previews.', max_length=300)),
                ('is_popular', models.BooleanField(default=False, help_text='ON → this post is listed in the POPULAR sidebar.')),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Date shown on cards and the detail page.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', 'display_order', '-id'],
                'indexes': [models.Index(fields=['is_active', '-published_date'], name='blog_blogpo_is_acti_c5e972_idx'), models.Index(fields=['is_popular', 'is_active'], name='blog_blogpo_is_popu_6b5401_idx')],
            },
        ),
    ]
