# Generated by Django 5.0.6 on 2026-07-01 06:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title if left blank. Used in the URL.', max_length=320, unique=True)),
                ('excerpt', models.CharField(help_text='Short preview line shown on the card / sidebar.', max_length=400)),
                ('author', models.CharField(default='Admin', help_text='By-line, e.g. "Admin".', max_length=120)),
                ('image', models.ImageField(help_text='Post image - used on the card, POPULAR sidebar and the detail page.', upload_to='blog/images/')),
                ('popular', models.BooleanField(default=False, help_text='ON -> this post appears in the POPULAR sidebar.')),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Shown as "Mar 20, 2026".')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', 'display_order', '-id'],
                'indexes': [models.Index(fields=['is_active', '-published_date'], name='blog_blogpo_is_acti_c5e972_idx'), models.Index(fields=['popular', 'is_active'], name='blog_blogpo_popular_ae48f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='One paragraph of the article (plain text).')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Paragraph',
                'verbose_name_plural': 'Content Paragraphs',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
