# Generated by Django 5.0.6 on 2026-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this post, e.g. https://www.tagsbikez.com/blogs/my-post. Falls back to FRONTEND_URL + /blogs/<slug>/ if blank.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Falls back to the excerpt if blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO <title> tag (max 70 chars). Falls back to the post title if blank.', max_length=70),
        ),
    ]
