# Generated by Django 5.0.6 on 2026-07-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_canonical_url_blogpost_meta_description_and_more'),
        ('blog', '0002_blogpost_seo_fields'),
    ]

    operations = [
    ]
