# Generated by Django 5.0.6 on 2026-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20260714_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Optional, comma separated (e.g. "yamaha fz, motorcycle review").', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='noindex',
            field=models.BooleanField(default=False, help_text='ON -> tells search engines NOT to index this post (adds a "noindex" meta tag).'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image used when the post is shared on social media (Facebook/X/WhatsApp). Falls back to the main post image if left blank. Recommended 1200x630px.', null=True, upload_to='blog/og_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Only set this if this content is duplicated from / syndicated to another URL.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Google search snippet. Falls back to the excerpt if left blank. Keep under ~155 characters.', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Browser tab / Google title. Falls back to the post title if left blank. Keep under ~60 characters.', max_length=70),
        ),
    ]
