# Generated by Django 5.0.6 on 2026-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='brochure_file',
            field=models.FileField(blank=True, help_text='Upload PDF brochure', null=True, upload_to='motorcycles/brochures/'),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='engine_cc',
            field=models.CharField(help_text='e.g. 349cc', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='power',
            field=models.CharField(help_text='e.g. 20.2 bhp', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='torque',
            field=models.CharField(help_text='e.g. 27 Nm', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='hex',
            field=models.CharField(help_text='e.g. #111111', max_length=10),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(help_text='e.g. Factory Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='price',
            field=models.CharField(help_text='e.g. ₹1,69,189', max_length=30),
        ),
    ]
