# Generated by Django 5.0.6 on 2026-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_alter_motorcycleproduct_brochure_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeaturesection',
            options={'ordering': ['display_order'], 'verbose_name': 'Product Feature Section', 'verbose_name_plural': 'Product Feature Sections (Bottom)'},
        ),
        migrations.AddField(
            model_name='motorcycleproduct',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='ON  → hides full detail page; shows "Coming Soon" badge on listing card.\nOFF → full detail page is accessible normally.'),
        ),
        migrations.AddField(
            model_name='motorcycleproduct',
            name='emi_starts_at',
            field=models.CharField(blank=True, help_text='e.g. ₹3,999/month  — shown as "EMI STARTS @" on listing card', max_length=100),
        ),
        migrations.AlterField(
            model_name='productfeaturesection',
            name='description',
            field=models.TextField(help_text='Feature description paragraph'),
        ),
        migrations.AlterField(
            model_name='productfeaturesection',
            name='image',
            field=models.ImageField(help_text='Feature highlight image', upload_to='motorcycles/features/'),
        ),
        migrations.AlterField(
            model_name='productfeaturesection',
            name='title',
            field=models.CharField(help_text='e.g. Twin-pod Console', max_length=200),
        ),
        migrations.AlterField(
            model_name='producttopabout',
            name='description',
            field=models.TextField(help_text='Paragraph shown below the heading'),
        ),
        migrations.AlterField(
            model_name='producttopabout',
            name='heading',
            field=models.CharField(help_text='e.g. Born to Ride', max_length=200),
        ),
        migrations.AlterField(
            model_name='producttopabout',
            name='top_image',
            field=models.ImageField(help_text='Hero image shown at the top of the product page', upload_to='motorcycles/top_about/'),
        ),
    ]
