# Generated by Django 5.0.6 on 2026-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_alter_productfeaturesection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycleproduct',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='emi_starts_at',
            field=models.CharField(blank=True, help_text='e.g. ₹3,999/month — shown as "EMI STARTS @" on listing card', max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='engine_cc',
            field=models.CharField(blank=True, help_text='e.g. 349cc', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='power',
            field=models.CharField(blank=True, help_text='e.g. 20.2 bhp', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycleproduct',
            name='torque',
            field=models.CharField(blank=True, help_text='e.g. 27 Nm', max_length=50),
        ),
    ]
