# Generated by Django 5.0.6 on 2026-05-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
    ]
