# Generated by Django 5.0.6 on 2026-05-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sales Department', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class e.g. 🛵', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career Department',
                'verbose_name_plural': 'Career Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Field Staff', max_length=200)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number with country code e.g. 919876543210', max_length=20)),
                ('whatsapp_message', models.CharField(blank=True, help_text='Pre-filled WhatsApp message. Leave blank to auto-generate.', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='careers.careerdepartment')),
            ],
            options={
                'verbose_name': 'Career Role',
                'verbose_name_plural': 'Career Roles',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
