# Generated by Django 5.0.6 on 2026-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerrole',
            name='whatsapp_message',
            field=models.CharField(blank=True, help_text='Pre-filled message. Leave blank to auto-generate from job title.', max_length=500),
        ),
        migrations.AlterField(
            model_name='careerrole',
            name='whatsapp_number',
            field=models.CharField(help_text='WhatsApp number with country code — digits only, no + or spaces. e.g. 919876543210', max_length=20),
        ),
    ]
